"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ikt^a-onq^k^h)6-74yj(6iccq4%v@xy4kbsjl)r0@6pvow2na'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', "10.0.2.2","8cfd-2800-2144-c200-2010-cc08-e78c-756f-594b.ngrok-free.app","2f03-2800-2144-c200-2010-cc08-e78c-756f-594b.ngrok-free.app","oriented-seemingly-drake.ngrok-free.app", "*"]  # Lista de hosts permitidos
CORS_ORIGIN_WHITELIST = ['http://localhost:4200', "https://2f03-2800-2144-c200-2010-cc08-e78c-756f-594b.ngrok-free.app","https://oriented-seemingly-drake.ngrok-free.app"]


CORS_ALLOWED_ORIGINS = ['http://localhost:4200',"https://2f03-2800-2144-c200-2010-cc08-e78c-756f-594b.ngrok-free.app","https://oriented-seemingly-drake.ngrok-free.app"]

CORS_ALLOW_CREDENTIALS = True
# settings.py
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecommerce',
    'api',
    'rest_framework',
    'corsheaders',
    'knox',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    


]

CORS_ALLOWED_ORIGINS = [
    'http://localhost',"https://2f03-2800-2144-c200-2010-cc08-e78c-756f-594b.ngrok-free.app", "https://oriented-seemingly-drake.ngrok-free.app"
    ]


CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {

'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'aceitososdb',
'USER': 'root',
'PASSWORD': '',
'HOST': 'localhost',
'PORT': '3306',
'OPTIONS': {
'sql_mode': 'traditional',
}
}
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'



MEDIA_URL ="/media/"
#MEDIA_ROOT = r'C:\Users\varga\OneDrive\Escritorio\aceitososWeb\back\ecommerce\api\media\products'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if 'ngrok' in ALLOWED_HOSTS:
    from django.middleware.security import SecurityMiddleware
    MIDDLEWARE.insert(1, 'django.middleware.security.SecurityMiddleware')



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        #'rest_framework.authentication.SessionAuthentication',// La autenticación se maneja con knox sino hay error de csrf porq django tiene por defecto
        'knox.auth.TokenAuthentication',
        ],
    
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', 
        'rest_framework.permissions.AllowAny' 
    ],
    
}

CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app", "https://oriented-seemingly-drake.ngrok-free.app"]

#CSRF_TRUSTED_ORIGINS = [
 #   "http://127.0.0.1:8000",
  #  "http://localhost:8000",
   # "http://192.168.0.145:8000"
#]

#CSRF_COOKIE_SECURE = False
#SESSION_COOKIE_SECURE = False
APPEND_SLASH = True